export const TOKEN_TYPES = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  ACCOUNT_VERIFICATION: 'ACCOUNT_VERIFICATION',
  SET_PASSWORD: 'SET_PASSWORD'
}

export const USER_TYPES = {
  ADMIN: 0
}
